---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo
  namespace: echo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/echo
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: echo
      interval: 1m
      
