---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-git
  namespace: default
spec:
  interval: 1m
  targetNamespace: podinfo-git
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: default
      interval: 1m
---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-git